"""Add AI insights and arbitrage tables

Revision ID: 0158ed6404e8
Revises: ea91250ea9f4
Create Date: 2026-01-04 18:40:02.205393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0158ed6404e8'
down_revision: Union[str, Sequence[str], None] = 'ea91250ea9f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_insights',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('market_id', sa.String(length=255), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('pattern_type', sa.String(length=100), nullable=True),
    sa.Column('recommendation', sa.String(length=50), nullable=False),
    sa.Column('confidence_score', sa.Integer(), nullable=False),
    sa.Column('one_liner', sa.Text(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('risk_factors', sa.JSON(), nullable=True),
    sa.Column('suggested_position', sa.String(length=20), nullable=True),
    sa.Column('edge_explanation', sa.Text(), nullable=True),
    sa.Column('time_sensitivity', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_insights_actionable', 'ai_insights', ['confidence_score', 'created_at'], unique=False, postgresql_where=sa.text('confidence_score > 60'))
    op.create_index('idx_insights_platform_recent', 'ai_insights', ['platform', 'created_at'], unique=False)
    op.create_index('idx_insights_recommendation', 'ai_insights', ['recommendation', 'created_at'], unique=False)
    op.create_index(op.f('ix_ai_insights_market_id'), 'ai_insights', ['market_id'], unique=False)
    op.create_table('arbitrage_opportunities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('opportunity_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('kalshi_market_id', sa.String(length=255), nullable=True),
    sa.Column('kalshi_market_title', sa.Text(), nullable=True),
    sa.Column('polymarket_market_id', sa.String(length=255), nullable=True),
    sa.Column('polymarket_market_title', sa.Text(), nullable=True),
    sa.Column('edge_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('execution_steps', sa.JSON(), nullable=True),
    sa.Column('risks', sa.JSON(), nullable=True),
    sa.Column('confidence_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_arbitrage_active', 'arbitrage_opportunities', ['created_at'], unique=False, postgresql_where=sa.text("status = 'active'"))
    op.create_index('idx_arbitrage_type', 'arbitrage_opportunities', ['opportunity_type', 'created_at'], unique=False)
    op.create_table('daily_digests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('digest_date', sa.DateTime(), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('top_picks', sa.JSON(), nullable=True),
    sa.Column('avoid_list', sa.JSON(), nullable=True),
    sa.Column('market_sentiment', sa.Text(), nullable=True),
    sa.Column('arbitrage_opportunities', sa.JSON(), nullable=True),
    sa.Column('watchlist', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_digest_date_tier', 'daily_digests', ['digest_date', 'tier'], unique=True)
    op.create_index(op.f('ix_daily_digests_digest_date'), 'daily_digests', ['digest_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_digests_digest_date'), table_name='daily_digests')
    op.drop_index('idx_digest_date_tier', table_name='daily_digests')
    op.drop_table('daily_digests')
    op.drop_index('idx_arbitrage_type', table_name='arbitrage_opportunities')
    op.drop_index('idx_arbitrage_active', table_name='arbitrage_opportunities', postgresql_where=sa.text("status = 'active'"))
    op.drop_table('arbitrage_opportunities')
    op.drop_index(op.f('ix_ai_insights_market_id'), table_name='ai_insights')
    op.drop_index('idx_insights_recommendation', table_name='ai_insights')
    op.drop_index('idx_insights_platform_recent', table_name='ai_insights')
    op.drop_index('idx_insights_actionable', table_name='ai_insights', postgresql_where=sa.text('confidence_score > 60'))
    op.drop_table('ai_insights')
    # ### end Alembic commands ###
