"""Add url column to markets table

Revision ID: 2e3d2a32e423
Revises: 6a40ccd62cfd
Create Date: 2026-01-09 03:37:27.716262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2e3d2a32e423'
down_revision: Union[str, Sequence[str], None] = '6a40ccd62cfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ai_insights', 'summary',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('ai_insights', 'risk_factors')
    op.drop_column('ai_insights', 'confidence_score')
    op.drop_column('ai_insights', 'one_liner')
    op.drop_column('ai_insights', 'pattern_type')
    op.drop_column('ai_insights', 'reasoning')
    op.drop_column('ai_insights', 'time_sensitivity')
    op.drop_column('ai_insights', 'suggested_position')
    op.drop_column('ai_insights', 'recommendation')
    op.drop_column('ai_insights', 'edge_explanation')
    op.alter_column('alerts', 'pattern_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('daily_digests', 'arbitrage_opportunities')
    op.drop_column('daily_digests', 'watchlist')
    op.drop_column('daily_digests', 'market_sentiment')
    op.drop_column('daily_digests', 'avoid_list')
    op.drop_column('daily_digests', 'top_picks')
    op.add_column('markets', sa.Column('url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('markets', 'url')
    op.add_column('daily_digests', sa.Column('top_picks', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('daily_digests', sa.Column('avoid_list', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('daily_digests', sa.Column('market_sentiment', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('daily_digests', sa.Column('watchlist', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('daily_digests', sa.Column('arbitrage_opportunities', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.alter_column('alerts', 'pattern_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('ai_insights', sa.Column('edge_explanation', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('ai_insights', sa.Column('recommendation', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('ai_insights', sa.Column('suggested_position', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('ai_insights', sa.Column('time_sensitivity', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('ai_insights', sa.Column('reasoning', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('ai_insights', sa.Column('pattern_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('ai_insights', sa.Column('one_liner', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('ai_insights', sa.Column('confidence_score', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ai_insights', sa.Column('risk_factors', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.alter_column('ai_insights', 'summary',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
